on: [push]
jobs:
  back_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Generate build
        run: npm run build

  front_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ui/
          npm install
        env:
          CI: true

      - name: Generate build
        run: |
          cd ui/
          npm run build

  style:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier
        run: npm run check-format

      - name: ESLint
        run: npm run lint
